[package]
name = "conspiracies"
version = "0.0.1"
authors = ["Rob Rowe <rrowe@foodlogiq.com>"]

[[bin]]
name = "db_loader"
path = "src/db_loader/main.rs" 

[dependencies]
clap = "2.31.2"
wikipedia = "0.3.1"