INSERT INTO links_processed (title) values ('The title was passed in: Conspiracy_theory (Hopefully, this is a Wikipage title).');
INSERT INTO links_processed (title) values ('SAVE ERROR: UNIQUE constraint failed: conspiracies.page_id Conspiracy_theory');
INSERT INTO links_processed (title) values ('1980 Camarate air crash');
INSERT INTO links_processed (title) values ('1986 Mozambican Tupolev Tu-134 crash');
INSERT INTO links_processed (title) values ('2006 O''Hare International Airport UFO sighting');
INSERT INTO links_processed (title) values ('2012 phenomenon');
INSERT INTO links_processed (title) values ('2013 Lahad Datu standoff');
INSERT INTO links_processed (title) values ('9/11');
INSERT INTO links_processed (title) values ('9/11 Truth movement');
INSERT INTO links_processed (title) values ('9/11 conspiracy theories');
INSERT INTO links_processed (title) values ('A Culture of Conspiracy');
INSERT INTO links_processed (title) values ('Acupuncture');
INSERT INTO links_processed (title) values ('Adelino Amaro da Costa');
INSERT INTO links_processed (title) values ('Adrian Vermeule');
INSERT INTO links_processed (title) values ('Agenda 21');
INSERT INTO links_processed (title) values ('Airey Neave');
INSERT INTO links_processed (title) values ('Alchemy');
INSERT INTO links_processed (title) values ('Alien abduction');
INSERT INTO links_processed (title) values ('Allegations of CIA assistance to Osama bin Laden');
INSERT INTO links_processed (title) values ('Alternative medicine');
INSERT INTO links_processed (title) values ('Amazon Standard Identification Number');
INSERT INTO links_processed (title) values ('American Historical Association');
INSERT INTO links_processed (title) values ('American Revolution');
INSERT INTO links_processed (title) values ('American history');
INSERT INTO links_processed (title) values ('Ancient astronauts');
INSERT INTO links_processed (title) values ('Anthroposophic medicine');
INSERT INTO links_processed (title) values ('Anti-statism');
INSERT INTO links_processed (title) values ('Anti-war');
INSERT INTO links_processed (title) values ('Apocalypticism');
INSERT INTO links_processed (title) values ('Apophenia');
INSERT INTO links_processed (title) values ('Applied kinesiology');
INSERT INTO links_processed (title) values ('Aquatic ape hypothesis');
INSERT INTO links_processed (title) values ('Arab');
INSERT INTO links_processed (title) values ('Area 51');
INSERT INTO links_processed (title) values ('Aryan race');
INSERT INTO links_processed (title) values ('Ashgate Publishing');
INSERT INTO links_processed (title) values ('Assassination');
INSERT INTO links_processed (title) values ('Assassination of Abraham Lincoln');
INSERT INTO links_processed (title) values ('Assassination of Archduke Franz Ferdinand of Austria');
INSERT INTO links_processed (title) values ('Assassination of Martin Luther King Jr.');
INSERT INTO links_processed (title) values ('Assassination of Olof Palme');
INSERT INTO links_processed (title) values ('Astrology');
INSERT INTO links_processed (title) values ('Attitude polarization');
INSERT INTO links_processed (title) values ('Avro Canada CF-105 Arrow');
INSERT INTO links_processed (title) values ('Barack Obama citizenship conspiracy theories');
INSERT INTO links_processed (title) values ('Barack Obama religion conspiracy theories');
INSERT INTO links_processed (title) values ('Bates method');
INSERT INTO links_processed (title) values ('Bermuda Triangle');
INSERT INTO links_processed (title) values ('Bernard Bailyn');
INSERT INTO links_processed (title) values ('Bible conspiracy theory');
INSERT INTO links_processed (title) values ('Bibliothèque nationale de France');
INSERT INTO links_processed (title) values ('Big Pharma conspiracy theory');
INSERT INTO links_processed (title) values ('Bilderberg Group');
INSERT INTO links_processed (title) values ('Biodynamic agriculture');
INSERT INTO links_processed (title) values ('Black Knight satellite conspiracy theory');
INSERT INTO links_processed (title) values ('Black genocide conspiracy theory');
INSERT INTO links_processed (title) values ('Black helicopter');
INSERT INTO links_processed (title) values ('Blog');
INSERT INTO links_processed (title) values ('Blood libel');
INSERT INTO links_processed (title) values ('Bloodletting');
INSERT INTO links_processed (title) values ('Body memory');
INSERT INTO links_processed (title) values ('Bohemian Grove');
INSERT INTO links_processed (title) values ('Bourgeois pseudoscience');
INSERT INTO links_processed (title) values ('Bruce Cumings');
INSERT INTO links_processed (title) values ('Bruno Latour');
INSERT INTO links_processed (title) values ('CIA Kennedy assassination conspiracy theory');
INSERT INTO links_processed (title) values ('Cabal');
INSERT INTO links_processed (title) values ('Cairo Fire');
INSERT INTO links_processed (title) values ('Cargo cult science');
INSERT INTO links_processed (title) values ('Carl Sagan');
INSERT INTO links_processed (title) values ('Cash-Landrum incident');
INSERT INTO links_processed (title) values ('Cass Sunstein');
INSERT INTO links_processed (title) values ('Catastrophism');
INSERT INTO links_processed (title) values ('Central Intelligence Agency');
INSERT INTO links_processed (title) values ('Charlatan');
INSERT INTO links_processed (title) values ('Chemtrail conspiracy theory');
INSERT INTO links_processed (title) values ('Chip Berlet');
INSERT INTO links_processed (title) values ('Chiropractic');
INSERT INTO links_processed (title) values ('Christopher Hitchens');
INSERT INTO links_processed (title) values ('Chromotherapy');
INSERT INTO links_processed (title) values ('Civil liberties');
INSERT INTO links_processed (title) values ('Clare Birchall');
INSERT INTO links_processed (title) values ('Climate change denial');
INSERT INTO links_processed (title) values ('Clockwork Orange (plot)');
INSERT INTO links_processed (title) values ('Cognitive dissonance');
INSERT INTO links_processed (title) values ('Colon cleansing');
INSERT INTO links_processed (title) values ('Committee for Skeptical Inquiry');
INSERT INTO links_processed (title) values ('Communal reinforcement');
INSERT INTO links_processed (title) values ('Confirmation bias');
INSERT INTO links_processed (title) values ('Conspiracy');
INSERT INTO links_processed (title) values ('Conspiracy: How the Paranoid Style Flourishes and Where It Comes From');
INSERT INTO links_processed (title) values ('Conspiracy (civil)');
INSERT INTO links_processed (title) values ('Conspiracy (criminal)');
INSERT INTO links_processed (title) values ('Conspiracy Encyclopedia');
INSERT INTO links_processed (title) values ('Conspiracy Encyclopedia: The Encyclopedia of Conspiracy Theories');
INSERT INTO links_processed (title) values ('Conspiracy fiction');
INSERT INTO links_processed (title) values ('Conspiracy theories about Adolf Hitler''s death');
INSERT INTO links_processed (title) values ('Conspiracy theories in Turkey');
INSERT INTO links_processed (title) values ('Conspiracy theories in the Arab world');
INSERT INTO links_processed (title) values ('Conspiracy theory (disambiguation)');
INSERT INTO links_processed (title) values ('Controversies about the 2004 Madrid train bombings');
INSERT INTO links_processed (title) values ('Conversion therapy');
INSERT INTO links_processed (title) values ('Council on Foreign Relations');
INSERT INTO links_processed (title) values ('Crank (person)');
INSERT INTO links_processed (title) values ('Creation science');
INSERT INTO links_processed (title) values ('Crime');
INSERT INTO links_processed (title) values ('Critical theory');
INSERT INTO links_processed (title) values ('Cryptoterrestrial hypothesis');
INSERT INTO links_processed (title) values ('Cryptozoology');
INSERT INTO links_processed (title) values ('Crystal healing');
INSERT INTO links_processed (title) values ('Cui bono');
INSERT INTO links_processed (title) values ('Cults of Unreason');
INSERT INTO links_processed (title) values ('Cultural phenomenon');
INSERT INTO links_processed (title) values ('Culture Machine');
INSERT INTO links_processed (title) values ('Dag Hammarskjöld');
INSERT INTO links_processed (title) values ('David Aaronovitch');
INSERT INTO links_processed (title) values ('David Icke');
INSERT INTO links_processed (title) values ('David Robert Grimes');
INSERT INTO links_processed (title) values ('Death and state funeral of Muhammad Zia-ul-Haq');
INSERT INTO links_processed (title) values ('Death of Diana, Princess of Wales');
INSERT INTO links_processed (title) values ('Death of Diana, Princess of Wales conspiracy theories');
INSERT INTO links_processed (title) values ('Death of Marilyn Monroe');
INSERT INTO links_processed (title) values ('Death of Subhas Chandra Bose');
INSERT INTO links_processed (title) values ('Deception');
INSERT INTO links_processed (title) values ('Denial');
INSERT INTO links_processed (title) values ('Denver International Airport');
INSERT INTO links_processed (title) values ('Der Spiegel');
INSERT INTO links_processed (title) values ('Derogatory');
INSERT INTO links_processed (title) values ('Detoxification (alternative medicine)');
INSERT INTO links_processed (title) values ('Dianetics');
INSERT INTO links_processed (title) values ('Digital object identifier');
INSERT INTO links_processed (title) values ('Discredited AIDS origins theories');
INSERT INTO links_processed (title) values ('Discredited HIV/AIDS origins theories');
INSERT INTO links_processed (title) values ('Doktor Koster's Antigaspills');
INSERT INTO links_processed (title) values ('Dorothy Kilgallen');
INSERT INTO links_processed (title) values ('Dowsing');
INSERT INTO links_processed (title) values ('Dreams from My Real Father');
INSERT INTO links_processed (title) values ('Dulce Base');
INSERT INTO links_processed (title) values ('Dulles' Plan');
INSERT INTO links_processed (title) values ('Dyatlov Pass incident');
INSERT INTO links_processed (title) values ('Ear candling');
INSERT INTO links_processed (title) values ('Electromagnetic hypersensitivity');
INSERT INTO links_processed (title) values ('Electronic Voice Phenomenon');
INSERT INTO links_processed (title) values ('Elvis sightings');
INSERT INTO links_processed (title) values ('Encyclopedia of Pseudoscience');
INSERT INTO links_processed (title) values ('Epistemology');
INSERT INTO links_processed (title) values ('Esotericism');
INSERT INTO links_processed (title) values ('Espionage');
INSERT INTO links_processed (title) values ('Estimate of the Situation');
INSERT INTO links_processed (title) values ('Eurabia');
INSERT INTO links_processed (title) values ('Extraterrestrial hypothesis');
INSERT INTO links_processed (title) values ('Eye of Providence');
INSERT INTO links_processed (title) values ('FBI Laboratory');
INSERT INTO links_processed (title) values ('FEMA camps conspiracy theory');
INSERT INTO links_processed (title) values ('Fads and Fallacies in the Name of Science');
INSERT INTO links_processed (title) values ('False flag');
INSERT INTO links_processed (title) values ('Falsifiability');
INSERT INTO links_processed (title) values ('Federal government of the United States');
INSERT INTO links_processed (title) values ('Feng shui');
INSERT INTO links_processed (title) values ('First Monday (journal)');
INSERT INTO links_processed (title) values ('Flat Earth');
INSERT INTO links_processed (title) values ('Folklore');
INSERT INTO links_processed (title) values ('Founding Fathers of the United States');
INSERT INTO links_processed (title) values ('Francisco de Sá Carneiro');
INSERT INTO links_processed (title) values ('Free energy suppression conspiracy theory');
INSERT INTO links_processed (title) values ('Fringe science');
INSERT INTO links_processed (title) values ('Fringe theory');
INSERT INTO links_processed (title) values ('Furtive fallacy');
INSERT INTO links_processed (title) values ('Genocide denial');
INSERT INTO links_processed (title) values ('Geoffrey Chaucer');
INSERT INTO links_processed (title) values ('Germ theory denialism');
INSERT INTO links_processed (title) values ('Ghost rockets');
INSERT INTO links_processed (title) values ('Global warming conspiracy theory');
INSERT INTO links_processed (title) values ('Graphology');
INSERT INTO links_processed (title) values ('HIV/AIDS denialism');
INSERT INTO links_processed (title) values ('Harvard University Press');
INSERT INTO links_processed (title) values ('Hearst Communications');
INSERT INTO links_processed (title) values ('Hello Garci scandal');
INSERT INTO links_processed (title) values ('Herbert Kitchener, 1st Earl Kitchener');
INSERT INTO links_processed (title) values ('High Frequency Active Auroral Research Program');
INSERT INTO links_processed (title) values ('Historical Social Research');
INSERT INTO links_processed (title) values ('Historical negationism');
INSERT INTO links_processed (title) values ('Historicism');
INSERT INTO links_processed (title) values ('Hoax');
INSERT INTO links_processed (title) values ('Hollow Earth');
INSERT INTO links_processed (title) values ('Holocaust denial');
INSERT INTO links_processed (title) values ('Homeopathy');
INSERT INTO links_processed (title) values ('Homintern');
INSERT INTO links_processed (title) values ('Homosexual recruitment');
INSERT INTO links_processed (title) values ('Humanistic psychology');
INSERT INTO links_processed (title) values ('Humorism');
INSERT INTO links_processed (title) values ('Hypernationalism');
INSERT INTO links_processed (title) values ('Illuminati');
INSERT INTO links_processed (title) values ('Indigo children');
INSERT INTO links_processed (title) values ('Institutional analysis');
INSERT INTO links_processed (title) values ('Integrated Authority File');
INSERT INTO links_processed (title) values ('Intelligent design');
INSERT INTO links_processed (title) values ('Interdimensional hypothesis');
INSERT INTO links_processed (title) values ('International Standard Book Number');
INSERT INTO links_processed (title) values ('International Standard Serial Number');
INSERT INTO links_processed (title) values ('Israel-related animal conspiracy theories');
INSERT INTO links_processed (title) values ('JSTOR');
INSERT INTO links_processed (title) values ('Jade Helm 15 conspiracy theories');
INSERT INTO links_processed (title) values ('James Randi Educational Foundation');
INSERT INTO links_processed (title) values ('Japhetic theory');
INSERT INTO links_processed (title) values ('Jesse Walker');
INSERT INTO links_processed (title) values ('Jesuit conspiracy theories');
INSERT INTO links_processed (title) values ('Jewish conspiracy');
INSERT INTO links_processed (title) values ('John Birch Society');
INSERT INTO links_processed (title) values ('John F. Kennedy');
INSERT INTO links_processed (title) values ('John F. Kennedy assassination');
INSERT INTO links_processed (title) values ('John F. Kennedy assassination conspiracy theories');
INSERT INTO links_processed (title) values ('John Wiley & Sons');
INSERT INTO links_processed (title) values ('Jonathan Vankin');
INSERT INTO links_processed (title) values ('Jonestown conspiracy theories');
INSERT INTO links_processed (title) values ('Journal of Libertarian Studies');
INSERT INTO links_processed (title) values ('Judeo-Masonic conspiracy theory');
INSERT INTO links_processed (title) values ('Junk science');
INSERT INTO links_processed (title) values ('Juscelino Kubitschek');
INSERT INTO links_processed (title) values ('Karl Popper');
INSERT INTO links_processed (title) values ('Kaspar Hauser');
INSERT INTO links_processed (title) values ('Kecksburg UFO incident');
INSERT INTO links_processed (title) values ('Kennedy assassination conspiracies');
INSERT INTO links_processed (title) values ('King''s College London');
INSERT INTO links_processed (title) values ('Knights Templar legends');
INSERT INTO links_processed (title) values ('Korean Air Lines Flight 007 alternative theories');
INSERT INTO links_processed (title) values ('Lee Harvey Oswald');
INSERT INTO links_processed (title) values ('Levitation (paranormal)');
INSERT INTO links_processed (title) values ('Library of Congress Control Number');
INSERT INTO links_processed (title) values ('Lilla Saltsjöbadsavtalet');
INSERT INTO links_processed (title) values ('List of conspiracy theories');
INSERT INTO links_processed (title) values ('List of political conspiracies');
INSERT INTO links_processed (title) values ('List of reported UFO sightings');
INSERT INTO links_processed (title) values ('List of topics characterized as pseudoscience');
INSERT INTO links_processed (title) values ('Locus of control');
INSERT INTO links_processed (title) values ('Lost Cosmonauts');
INSERT INTO links_processed (title) values ('Love Jihad');
INSERT INTO links_processed (title) values ('Lunar effect');
INSERT INTO links_processed (title) values ('Lysenkoism');
INSERT INTO links_processed (title) values ('MS Estonia');
INSERT INTO links_processed (title) values ('Machiavellian');
INSERT INTO links_processed (title) values ('Magnet therapy');
INSERT INTO links_processed (title) values ('Mainstream media');
INSERT INTO links_processed (title) values ('Majestic 12');
INSERT INTO links_processed (title) values ('Malaysia Airlines Flight 17');
INSERT INTO links_processed (title) values ('Malaysia Airlines Flight 370 unofficial disappearance theories');
INSERT INTO links_processed (title) values ('Manichaeism');
INSERT INTO links_processed (title) values ('Mantell UFO incident');
INSERT INTO links_processed (title) values ('Marxist');
INSERT INTO links_processed (title) values ('Masonic conspiracy theories');
INSERT INTO links_processed (title) values ('Mass hysteria');
INSERT INTO links_processed (title) values ('Mass media');
INSERT INTO links_processed (title) values ('Maury Island incident');
INSERT INTO links_processed (title) values ('Mean world syndrome');
INSERT INTO links_processed (title) values ('Mediumship');
INSERT INTO links_processed (title) values ('Melanin theory');
INSERT INTO links_processed (title) values ('Men in black');
INSERT INTO links_processed (title) values ('Michael Barkun');
INSERT INTO links_processed (title) values ('Michael Collins (Irish leader)');
INSERT INTO links_processed (title) values ('Michael Kelly (editor)');
INSERT INTO links_processed (title) values ('Michael Shermer');
INSERT INTO links_processed (title) values ('Millenarianism');
INSERT INTO links_processed (title) values ('Milton William Cooper');
INSERT INTO links_processed (title) values ('Montauk Project');
INSERT INTO links_processed (title) values ('Moon landing conspiracy theories');
INSERT INTO links_processed (title) values ('Murder of Seth Rich');
INSERT INTO links_processed (title) values ('Murray Rothbard');
INSERT INTO links_processed (title) values ('Naomi Wolf');
INSERT INTO links_processed (title) values ('Naturopathy');
INSERT INTO links_processed (title) values ('Nazi UFOs');
INSERT INTO links_processed (title) values ('Nazi archaeology');
INSERT INTO links_processed (title) values ('Nepalese royal massacre');
INSERT INTO links_processed (title) values ('New Chronology (Fomenko)');
INSERT INTO links_processed (title) values ('New Coke');
INSERT INTO links_processed (title) values ('New World Order (conspiracy theory)');
INSERT INTO links_processed (title) values ('Nibiru cataclysm');
INSERT INTO links_processed (title) values ('Noam Chomsky');
INSERT INTO links_processed (title) values ('North American Union');
INSERT INTO links_processed (title) values ('Numerology');
INSERT INTO links_processed (title) values ('ODESSA');
INSERT INTO links_processed (title) values ('October Surprise conspiracy theory');
INSERT INTO links_processed (title) values ('Oklahoma City bombing conspiracy theories');
INSERT INTO links_processed (title) values ('On the Origin of the "Influencing Machine" in Schizophrenia');
INSERT INTO links_processed (title) values ('Open Humanities Press');
INSERT INTO links_processed (title) values ('Operation Gladio');
INSERT INTO links_processed (title) values ('Orgone');
INSERT INTO links_processed (title) values ('Osama Bin Laden');
INSERT INTO links_processed (title) values ('Osama bin Laden death conspiracy theories');
INSERT INTO links_processed (title) values ('Oxford English Dictionary');
INSERT INTO links_processed (title) values ('Oxford University Press');
INSERT INTO links_processed (title) values ('PLOS ONE');
INSERT INTO links_processed (title) values ('PRISM (surveillance program)');
INSERT INTO links_processed (title) values ('Pan Am Flight 103 conspiracy theories');
INSERT INTO links_processed (title) values ('Paranoia');
INSERT INTO links_processed (title) values ('Paranormal');
INSERT INTO links_processed (title) values ('Pathological science');
INSERT INTO links_processed (title) values ('Patrice Lumumba');
INSERT INTO links_processed (title) values ('Paul is dead');
INSERT INTO links_processed (title) values ('Pearl Harbor advance-knowledge conspiracy theory');
INSERT INTO links_processed (title) values ('Perpetual motion');
INSERT INTO links_processed (title) values ('Phantom time hypothesis');
INSERT INTO links_processed (title) values ('Phar Lap');
INSERT INTO links_processed (title) values ('Philadelphia Experiment');
INSERT INTO links_processed (title) values ('Phoenix Lights');
INSERT INTO links_processed (title) values ('Phrenology');
INSERT INTO links_processed (title) values ('Pizzagate conspiracy theory');
INSERT INTO links_processed (title) values ('Polygraph');
INSERT INTO links_processed (title) values ('Pope John Paul I conspiracy theories');
INSERT INTO links_processed (title) values ('Praeger Publishers');
INSERT INTO links_processed (title) values ('Primal therapy');
INSERT INTO links_processed (title) values ('Princes in the Tower');
INSERT INTO links_processed (title) values ('Princeton University Press');
INSERT INTO links_processed (title) values ('Project Azorian');
INSERT INTO links_processed (title) values ('Project Serpo');
INSERT INTO links_processed (title) values ('Pseudoarchaeology');
INSERT INTO links_processed (title) values ('Pseudohistory');
INSERT INTO links_processed (title) values ('Pseudoscience');
INSERT INTO links_processed (title) values ('Pseudoscientific metrology');
INSERT INTO links_processed (title) values ('Psychohistory');
INSERT INTO links_processed (title) values ('Psychological projection');
INSERT INTO links_processed (title) values ('PubMed Central');
INSERT INTO links_processed (title) values ('PubMed Identifier');
INSERT INTO links_processed (title) values ('QAnon');
INSERT INTO links_processed (title) values ('Quackery');
INSERT INTO links_processed (title) values ('Quackwatch');
INSERT INTO links_processed (title) values ('Quantum mysticism');
INSERT INTO links_processed (title) values ('RMS Lusitania');
INSERT INTO links_processed (title) values ('RMS Titanic alternative theories');
INSERT INTO links_processed (title) values ('Randomness');
INSERT INTO links_processed (title) values ('Reconquista (Mexico)');
INSERT INTO links_processed (title) values ('Recovered-memory therapy');
INSERT INTO links_processed (title) values ('Red Scare');
INSERT INTO links_processed (title) values ('Red mercury');
INSERT INTO links_processed (title) values ('Redemption movement');
INSERT INTO links_processed (title) values ('Reichstag fire');
INSERT INTO links_processed (title) values ('Reiki');
INSERT INTO links_processed (title) values ('Religious fundamentalism');
INSERT INTO links_processed (title) values ('Rendlesham Forest incident');
INSERT INTO links_processed (title) values ('Reptilians');
INSERT INTO links_processed (title) values ('Richard Hofstadter');
INSERT INTO links_processed (title) values ('Robert F. Kennedy assassination conspiracy theories');
INSERT INTO links_processed (title) values ('Roger Cohen');
INSERT INTO links_processed (title) values ('Roswell UFO incident');
INSERT INTO links_processed (title) values ('Rothschild family');
INSERT INTO links_processed (title) values ('Rumours and conspiracy theories about the July 2005 London bombings');
INSERT INTO links_processed (title) values ('SARS conspiracy theory');
INSERT INTO links_processed (title) values ('Sandy Hook Elementary School shooting conspiracy theories');
INSERT INTO links_processed (title) values ('Satanic ritual abuse');
INSERT INTO links_processed (title) values ('Schizophrenia');
INSERT INTO links_processed (title) values ('Scientific racism');
INSERT INTO links_processed (title) values ('Search engine');
INSERT INTO links_processed (title) values ('Secrecy');
INSERT INTO links_processed (title) values ('Secret society');
INSERT INTO links_processed (title) values ('September 11 attacks');
INSERT INTO links_processed (title) values ('September 11 attacks advance-knowledge conspiracy theories');
INSERT INTO links_processed (title) values ('Sergey Kirov');
INSERT INTO links_processed (title) values ('Sheeple');
INSERT INTO links_processed (title) values ('Skeptical Inquirer');
INSERT INTO links_processed (title) values ('Skull and Bones');
INSERT INTO links_processed (title) values ('Snake oil');
INSERT INTO links_processed (title) values ('Social media');
INSERT INTO links_processed (title) values ('Sociologist');
INSERT INTO links_processed (title) values ('Soft coup');
INSERT INTO links_processed (title) values ('Sovereign citizen movement');
INSERT INTO links_processed (title) values ('Suicide of Kurt Cobain');
INSERT INTO links_processed (title) values ('Suicide of Vince Foster');
INSERT INTO links_processed (title) values ('Superseded scientific theories');
INSERT INTO links_processed (title) values ('Suppressed research in the Soviet Union');
INSERT INTO links_processed (title) values ('Système universitaire de documentation');
INSERT INTO links_processed (title) values ('TWA Flight 800 conspiracy theories');
INSERT INTO links_processed (title) values ('Temple Denial');
INSERT INTO links_processed (title) values ('The American Historical Review');
INSERT INTO links_processed (title) values ('The Fellowship (Christian organization)');
INSERT INTO links_processed (title) values ('The Hidden Hand: Middle East Fears of Conspiracy');
INSERT INTO links_processed (title) values ('The Ideological Origins of the American Revolution');
INSERT INTO links_processed (title) values ('The New York Times');
INSERT INTO links_processed (title) values ('The Open Society and Its Enemies');
INSERT INTO links_processed (title) values ('The Paranoid Style in American Politics');
INSERT INTO links_processed (title) values ('The Protocols of the Elders of Zion');
INSERT INTO links_processed (title) values ('The Psychology of the Occult');
INSERT INTO links_processed (title) values ('The Ragged Edge of Science');
INSERT INTO links_processed (title) values ('The Skeptic''s Dictionary');
INSERT INTO links_processed (title) values ('The Skeptic Encyclopedia of Pseudoscience');
INSERT INTO links_processed (title) values ('The Wall Street Journal');
INSERT INTO links_processed (title) values ('Time (magazine)');
INSERT INTO links_processed (title) values ('Totalitarianism');
INSERT INTO links_processed (title) values ('Traditional medicine');
INSERT INTO links_processed (title) values ('Trepanning');
INSERT INTO links_processed (title) values ('Trilateral Commission');
INSERT INTO links_processed (title) values ('True-believer syndrome');
INSERT INTO links_processed (title) values ('Tunguska event');
INSERT INTO links_processed (title) values ('Tuskegee Syphilis Experiment');
INSERT INTO links_processed (title) values ('UFO conspiracy theory');
INSERT INTO links_processed (title) values ('USS Liberty incident');
INSERT INTO links_processed (title) values ('USS Maine (ACR-1)');
INSERT INTO links_processed (title) values ('Ufology');
INSERT INTO links_processed (title) values ('United States bombing of the Chinese embassy in Belgrade');
INSERT INTO links_processed (title) values ('University of Kent');
INSERT INTO links_processed (title) values ('Urban legend');
INSERT INTO links_processed (title) values ('Vaccine controversies');
INSERT INTO links_processed (title) values ('Varginha UFO incident');
INSERT INTO links_processed (title) values ('Vast right-wing conspiracy');
INSERT INTO links_processed (title) values ('Vatican conspiracy theories');
INSERT INTO links_processed (title) values ('Vela Incident');
INSERT INTO links_processed (title) values ('Vietnam War POW/MIA issue');
INSERT INTO links_processed (title) values ('Voice stress analysis');
INSERT INTO links_processed (title) values ('Voodoo science');
INSERT INTO links_processed (title) values ('War against Islam');
INSERT INTO links_processed (title) values ('War on terrorism');
INSERT INTO links_processed (title) values ('Washington Post');
INSERT INTO links_processed (title) values ('Water fluoridation controversy');
INSERT INTO links_processed (title) values ('Watergate');
INSERT INTO links_processed (title) values ('Wayback Machine');
INSERT INTO links_processed (title) values ('Widerøe Flight 933');
INSERT INTO links_processed (title) values ('World Trade Center controlled demolition conspiracy theories');
INSERT INTO links_processed (title) values ('World War I');
INSERT INTO links_processed (title) values ('World Wide Web');
INSERT INTO links_processed (title) values ('Władysław Sikorski''s death controversy');
INSERT INTO links_processed (title) values ('Yemenite Children Affair');
INSERT INTO links_processed (title) values ('Yitzhak Rabin assassination conspiracy theories');
INSERT INTO links_processed (title) values ('YouTube');
INSERT INTO links_processed (title) values ('Zamboanga City crisis');
INSERT INTO links_processed (title) values ('Zionism');
